
from qdrant_client import QdrantClient
from langchain_ollama import OllamaEmbeddings
from prompts import analyst_prompt
import json
from Agent.main import llm
from Agent.main import AgentState


def analyzer(state: AgentState):
    print("---ANALYZING RESULTS---")
    # This is where your analyze_results function will live
    
    print("--- EXECUTING ANALYST & ITERATION NODE ---")
    
    user_query = state.get("user_query", "")
    planner_queries = state.get("planner_queries", []) # Queries generated by planner node
    iteration_count = state.get("iteration_count", 0)
    
    # 1. Gather Context from Qdrant using the Planner's Queries
    client = QdrantClient(url="http://localhost:6333")
    embeddings_model = OllamaEmbeddings(model="qwen2.5:1.5b")
    collection_name = "research_docs"
    
    retrieved_chunks = []
    
    for query in planner_queries:
        query_vector = embeddings_model.embed_query(query)
        search_results = client.search(
            collection_name=collection_name,
            query_vector=query_vector,
            limit=2
        )
        
        for result in search_results:
            payload = result.payload
            retrieved_chunks.append(payload.get('parent_text', ''))
            
    unified_context = "\n\n---\n\n".join(list(set(retrieved_chunks)))
    
    
    formatted_analyst_prompt = analyst_prompt.substitute(
        user_query=user_query,
        unified_context=unified_context,
        iteration_count=iteration_count
    )
    try:
        response = llm.invoke(formatted_analyst_prompt)
        analysis_json = json.loads(response.content)
        
        print(f"Analyst confidence: {analysis_json['confidence_score']}%")
        print(f"-> Next Action: {analysis_json['loop_decision']}")
        
        return {
                "final_answer": analysis_json["current_summary"],
                "missing_report": analysis_json["missing_details_report"],
                "confidence_score": int(analysis_json["confidence_score"]),
                "loop_decision": analysis_json["loop_decision"],
                "iteration_count": iteration_count + 1 # Increment execution flag counter
            }
    except Exception as e:
        print(f"Error during analysis: {e}")
        return {
            "final_answer": "Analysis failed. No summary available.",
            "missing_report": "Unable to determine missing details due to analysis failure.",
            "confidence_score": 0,
            "loop_decision": "TERMINATE",
        }
