from qdrant_client import QdrantClient
import json
import traceback

try:
    from state import AgentState
    from models import llm
    from embeddings import get_embeddings
    from config import COLLECTION_NAME
    from prompts import analyst_prompt, gap_prompt
except ImportError:
    from Agent.state import AgentState
    from Agent.models import llm
    from Agent.embeddings import get_embeddings
    from Agent.config import COLLECTION_NAME
    from Agent.prompts import analyst_prompt, gap_prompt

THRESHOLD = 0.70

def analyzer(state: AgentState):
    print("---ANALYZING RESULTS---")
    print("--- EXECUTING ANALYST & ITERATION NODE ---")
    
    user_query = state.get("user_query", "")
    search_queries = state.get("search_queries", []) # Queries generated by planner node
    iteration_count = state.get("iteration_count", 0)
    
    retrieved_chunks = []
    
    try:
        client = QdrantClient(url="http://localhost:6333", timeout=5)
        EmbeddingsGenerator = get_embeddings()
        for query in search_queries:
            query_vector = EmbeddingsGenerator.embed_documents([query])[0]
            
            if hasattr(client, "query_points"):
                search_results = client.query_points(
                    collection_name=COLLECTION_NAME,
                    query=query_vector,
                    limit=2
                ).points
            elif hasattr(client, "search"):
                search_results = client.search(
                    collection_name=COLLECTION_NAME,
                    query_vector=query_vector,
                    limit=2
                )
            else:
                search_results = []
            
            for result in search_results:
                payload = getattr(result, "payload", {}) or {}
                parent_id = payload.get("parent_id")
                parent_text = payload.get("parent_text")
                if parent_id and parent_text:
                    retrieved_chunks.append((parent_id, parent_text))
    except Exception as e:
        print(f"[Analyst Qdrant Warning]: Vector search skipped ({e}). Operating with direct context.")

    seen_parent_ids = set()
    unique_chunks = []
    for parent_id, parent_text in retrieved_chunks:
        if parent_id not in seen_parent_ids:
            seen_parent_ids.add(parent_id)
            unique_chunks.append(parent_text)

    # Keep enough evidence for analysis while leaving the model room to finish its JSON.
    unified_context = "\n\n---\n\n".join(unique_chunks)[:12000]
    
    formatted_analyst_prompt = analyst_prompt.substitute(
        user_query=user_query,
        unified_context=unified_context,
        planner_queries=search_queries
    )    
    
    try:
        response = llm.invoke(formatted_analyst_prompt)
        try:
            analysis_json = json.loads(response.content)
        except json.JSONDecodeError as e:
            print(f"Analyst returned invalid or truncated JSON: {e}")
            retry_prompt = (
                f"{formatted_analyst_prompt}\n\n"
                "Return only a compact valid JSON object. Keep research_report under "
                "150 words and reasoning_for_score under 20 words. Do not use markdown "
                "or unescaped quotation marks inside string values."
            )
            retry_response = llm.invoke(retry_prompt)
            analysis_json = json.loads(retry_response.content)
        
        confidence = float(analysis_json.get("confidence_score", 0.0))
        loop_decision = "TERMINATE"
        
        print(f"Analyst confidence: {confidence * 100}%")
        print(f"Reasoning for confidence: {analysis_json.get('reasoning_for_score', 'N/A')}")
        
        gap_response = None
        if confidence < THRESHOLD:
            formatted_gap_prompt = gap_prompt.substitute(
                user_query=user_query,
                planner_queries=search_queries,
                confidence=confidence
            )
            gap_response = llm.invoke(formatted_gap_prompt)
            loop_decision = "CONTINUE"
        
        print(f"-> Next Action: {loop_decision}")
        
        report_text = analysis_json.get("research_report", analysis_json.get("current_summary", "No summary generated."))
        
        return {
            "final_answer": report_text,
            "missing_report": gap_response.content if gap_response else "No gap analysis needed. Confidence above threshold.",
            "confidence_score": confidence,
            "loop_decision": loop_decision,
            "iteration_count": iteration_count + 1 # Increment execution flag counter
        }
    except Exception as e:
        print(f"Error during analysis: {e}")
        traceback.print_exc()
        return {
            "final_answer": "Analysis failed. No summary available.",
            "missing_report": "Unable to determine missing details due to analysis failure.",
            "confidence_score": 0.0,
            "loop_decision": "TERMINATE",
        }

